// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCd_sBj4QLgZQxsv673Vz3_HvW4ZyVt4h8',
    appId: '1:164947820549:web:06e05b38fa1e0cb2aa9c6c',
    messagingSenderId: '164947820549',
    projectId: 'taskapp-193bc',
    authDomain: 'taskapp-193bc.firebaseapp.com',
    databaseURL: 'https://taskapp-193bc-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'taskapp-193bc.appspot.com',
    measurementId: 'G-MKC0RR44RM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGQoeZXQncuZRWnOMqhUTUkS7QNNFfJ8Q',
    appId: '1:164947820549:android:857f629e38da9eebaa9c6c',
    messagingSenderId: '164947820549',
    projectId: 'taskapp-193bc',
    databaseURL: 'https://taskapp-193bc-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'taskapp-193bc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCr0_TGmoUDfG5xa_lWki2pwMKr6FdPfNE',
    appId: '1:164947820549:ios:5483ab704224dc78aa9c6c',
    messagingSenderId: '164947820549',
    projectId: 'taskapp-193bc',
    databaseURL: 'https://taskapp-193bc-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'taskapp-193bc.appspot.com',
    iosClientId: '164947820549-9bp6dbhsc14oe5kf6f372dhg300hgbit.apps.googleusercontent.com',
    iosBundleId: 'com.example.fireapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCr0_TGmoUDfG5xa_lWki2pwMKr6FdPfNE',
    appId: '1:164947820549:ios:53d438926ad57afeaa9c6c',
    messagingSenderId: '164947820549',
    projectId: 'taskapp-193bc',
    databaseURL: 'https://taskapp-193bc-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'taskapp-193bc.appspot.com',
    iosClientId: '164947820549-di2s0uumc81qmbh0vpgt8bjsk8pmr220.apps.googleusercontent.com',
    iosBundleId: 'com.example.fireapp.RunnerTests',
  );
}
